musikundkultur/wohnzimmer

.gitignore, Dockerfile
This makes docker layer caching possible and will speed up local image builds already.
For leveraging the caching in GitHub actions, we need to do some updates to the workflows. This will be done separately.
=> chore(build): use `cargo-chef` to enable caching in docker builds

.github/workflows/release.yml
Adds a step to the release workflow which automatically builds and pushes a docker image to ghcr.io. The resulting docker image is then deployed via flyctl without rebuilding it.
The GitHub actions docker cache is leveraged to speed up the docker builds.
=> chore(release): build and push docker image

.github/CODEOWNERS
Referencing an organization is invalid, it has to be either a team or a user reference.
=> fix(meta): correct team reference in `CODEOWNERS`

.dockerignore, .gitignore, Cargo.lock, Cargo.toml, Dockerfile, README.md, config/default.toml, config/development.toml, config/production.toml, fly.toml, src/lib.rs, src/main.rs, templates/layout.html
Makes use of [`config-rs`](https://github.com/mehcode/config-rs) to implement hierarchical configuration from files and environment variables. This makes `clap` obsolete.
In the future we'll have more configuration options, e.g. when we add calendar support for events. Also we need to be able to configure things canonical URLs (for SEO) which are only relevant in production.
=> feat: add hierarchical application config

Cargo.lock, Cargo.toml, config/default.toml, src/calendar.rs, src/lib.rs, src/main.rs, templates/index.html
Adds an `EventSource` trait which allows the implementation of multiple sources for calendar events.
Right now only `StaticEventSource` was implemented to use a static list of events from the config. This is mostly useful during testing and development.
Later, we want to also add an `EventSource` for the Google Calendar which should be used in production.
Please note that the API for the `EventSource` trait is just an initial draft. We can obviously change it once we see what's needed by Google Calendar. I already designed it to be `async` though, because we'll need that later.
=> feat(calendar): add `EventSource` abstraction

config/production.toml, src/lib.rs, src/main.rs, templates/layout.html
If a `canonical_url` is configured in the `site` config, the `link` tag with the canonical URL will be added to the HTML head.
This is only relevant for SEO, here's what Google has to say about this: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls
I don't like the way we pass down the `request_path` into the template. In the best case I'd like to have this done implicitly somehow. Otherwise we will need to do this for every endpoint and it's easy to forget.
=> chore: add support for canonical `link` tag

Cargo.lock, Cargo.toml, config/default.toml, config/production.toml, src/calendar.rs, src/lib.rs, src/main.rs
This adds the `CachedEventSource` which wraps the underlying event source and will cache the results of `get_events` using the date range as cache key. It will also refresh the cache in the background if possible.
=> feat(calendar): add caching layer

Cargo.lock, Cargo.toml, examples/calendar-example.rs, src/calendar.rs, src/calendar/google/mod.rs, src/main.rs
This manually performs the version bump proposed by dependabot in https://github.com/musikundkultur/wohnzimmer/pull/43 because there were so many breaking changes that needed to be resolved manually.
Main changes:
- We don't need to manually handle token refresh anymore because the `TokenSource` does this transparently for us.
- Remove the `calendar_id` argument from the `GoogleCalendarClient` constructor since we always pull it from env at the moment.
- Some methods were converted to be `async` because of async dependencies.
- `ClientError` variants and messages were improved according to best practices (e.g. removed verbose `Error` suffix).
Closes #43.
=> chore(deps): bump google-cloud-auth from 0.6.1 to 0.9.1

Cargo.lock, Cargo.toml, config/default.toml, config/production.toml, src/calendar.rs, src/lib.rs, src/main.rs
We're periodically fetching all events from the event source instead of smaller ranges. This makes quite a bit of code and the whole caching layer obsolete.
It also avoids the first request to the homepage on a given day from taking too long, because there's no such thing as cache misses anymore.
=> feat(calendar): switch to periodic sync

Cargo.lock, Cargo.toml, src/calendar/google/mod.rs, src/calendar/templating.rs, src/main.rs
bump actix-files from 0.6.2 to 0.6.6
drop actix-web-labs as used functionality is part of actix-web now bump anyhow from 1.0.75 to 1.0.95
bump async-trait from 0.1.68 to 0.1.83
bump chono form 0.4.31 to 0.4.39
bump indexmap from 2.0.0 to 2.7.0
bump minijinja from 1.0.10 to 2.5.0
bump minijinja-autoreload from 1.0.10 to 2.5.0
bump serde from 1.0.164 to 1.0.217
bump thiserror from 1.0.50 to 2.0.9
bump google-cloud-auth from 0.13.0 to 0.17.2
bump google-cloud-token from 0.1.0 to 0.1.2
bump reqwest from 0.11 to 0.12
bump reqwest-middleware from 0.2.4 to 0.4
add http 1.2 and drop task-local-extensions as reqwest middleware switched this dependency bump tokio from 1.29.1 to 1.42.0
=> chore(deps): bump dependencies

.github/workflows/build-image.yml
This will eventually replace the build step within the release workflow. It also now builds the image on every PR to ensure that dependency updates don't break the docker build.
=> ci: add new workflow to build image

.github/workflows/ci.yml
Usage of ubuntu-20.04 is deprecated.
=> ci: use ubuntu-latest everywhere

.github/workflows/container.yml
This simplifies the release process and also makes rollbacks easier.
The release process docs in README.md need to be adjusted, but I'd like to postpone this until I'm done with the restructuring because there will be more PRs related to that.
=> ci: always deploy application on tags and pushes to main

Cargo.lock, Cargo.toml, examples/calendar-example.rs, fly.toml, src/calendar.rs, src/calendar/google/mod.rs, src/calendar/google/models.rs, src/calendar/templating.rs, src/main.rs
First of all, jiff has a nicer to work with API, and second, this makes it harded to make mistakes when working with zoned timestamps.
It also gets rid of some transitive dependencies and forces the correct timezone for the container to avoid running into surprises.
=> feat: switch from chrono to jiff

.github/workflows/ci.yml, .github/workflows/deploy.yml
This fixes some concurrency issues when multiple PR are merged and the deploy job is triggered in parallel, leading to fly.io errors because of a parallel deployment.
By splitting these workflows, we can leverage the `concurrency` config to ensure there's only one run of the deploy workflow at any given time. Additionally, we now also limit job concurrency at a PR level so that multiple quick pushes result in fewer job runs.
=> ci: use separate deploy workflow

Cargo.lock, Cargo.toml, config/default.toml, config/development.toml, examples/calendar-example.rs, src/calendar.rs, src/calendar/google/mod.rs, src/lib.rs, src/main.rs, src/metrics.rs
- Adds a metrics endpoint at `/metrics` if metrics are enabled in the config.
- Metrics endpoint optionally supports Bearer token auth so we can protect it properly when making it public.
- Custom metrics:
- Custom metric `wohnzimmer_calendar_syncs_total` (counter): increases every time a sync was performed (`status` label with values `success` or `error`).
- Custom metric `wohnzimmer_calendar_events` (gauge): number of calender events fetched during the last sync (no labels).
- Standard metrics: HTTP metrics and process metrics.
What's left to expose metrics in production (can be a separate PR):
- Production config needs to updated to expose the metrics endpoint. Right now it has `metrics.enabled = false`.
- Configure a Bearer token for the metrics endpoint via the `METRICS__TOKEN` …
=> feat: add prometheus metrics

src/main.rs
The prometheus process collector is only available on linux, which made the app fail to compile on macos.
=> fix: add support for development on macos

src/calendar.rs, src/metrics.rs
This metric contains the UNIX timestamp of the latest successful calendar sync.
Additionally, this change renames a couple of internal fields and methods to make them more concise.
=> feat(metrics): add `calendar_latest_sync_seconds`

src/calendar/templating.rs
- Fix bug where `>` was used instead of `>=` to compare if the end date is more than 24h after the start date.
- Also display the short weekday as part of the date now that we sometimes have events on wednesday and sunday in the calendar.
- Before: `5. Februar`
- After: `Mi, 5. Februar`
- Add tests for the custom calendar templating.
=> feat: improve date formatting

Cargo.lock, Cargo.toml, src/calendar/google/mod.rs
This original crate was handed over to Google, but contains a completely different implementation now:
https://github.com/googleapis/google-cloud-rust/blob/main/src/auth/README.md
From the README:
> This crate used to contain a different implementation, with a different
> surface. [@yoshidan](https://github.com/yoshidan) generously donated the crate
> name to Google. Their crate continues to live as [gcloud-auth](https://crates.io/crates/gcloud-auth).
=> chore(deps): rename google-cloud-auth to gcloud-auth

Cargo.lock
Fixes a dependabot security alert.
=> fix(deps): update rust crate openssl to v0.10.71
